baseURL = 'https://foxihd.github.io/hugo-brewm/'
title = ' PRISM'
theme = 'hugo-brewm'
# enableGitInfo = true
canonifyURLs = true
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
enableMissingTranslationPlaceholders = true
# sectionPagesMenu = 'main'
ignoreFiles = ['\.bak$', '\.redacted$']
ignoreLogs = ['err-youtube-remote']
copyright = 'Copyright (c) David Rutkevich'

## Enable flowlines
flowlines = true
## Limit number of flowlines
flowlinesLimit = 21

## Enable text justification
justifying = false
## Disable paragraph indentation
noIndent = false
## Show colophon section (including QR code)
colophon = false

[markup]
    [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 4

    [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true # NOT-RECOMMENDED! FOR DEMO PURPOSE ONLY!

[frontmatter]
    date = ['tanggal', ':default']
    expiryDate = ['redacted', 'kadaluwarsa', 'ditarik', ':default']
    lastmod = ['errata', 'addendum', "lastmod", 'disunting', 'diubah', ':default'] # ":fileModTime"