[[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/DavidRutkevich"
    pre = "github"
    
[[menu.main]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/davidrutkevich/"
    pre = "linkedin"
